name: Auto Approve

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
